# -*- coding: utf-8 -*-
"""Final_Project_ITP-DS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ddoe_vUfFhuyBAtQYTckpOOzagosUunC
"""

# Install the matplotlib library using pip.
pip install matplotlib

#install the plotly library using pip
pip install plotly

#create a directory - dataviztoolkit
!mkdir dataviztoolkit

# Create an empty __init__.py file in the dataviztoolkit directory
!touch dataviztoolkit/__init__.py

# Create a Python script file named chart_builder.py in the dataviztoolkit directory
!touch dataviztoolkit/chart_builder.py

# Create a Python script file named interactive_map.py in the dataviztoolkit directory
!touch dataviztoolkit/interactive_map.py

# Create a Python script file named custom_themes.py in the dataviztoolkit directory
!touch dataviztoolkit/custom_themes.py

# Create a subdirectory named Project_code inside the dataviztoolkit directory
!mkdir dataviztoolkit/Project_code

# Create a Python script file named chart_builder_main.py inside the Project_code subdirectory
!touch dataviztoolkit/Project_code/chart_builder_main.py

# Create a Python script file named interactive_map_main.py inside the Project_code subdirectory
!touch dataviztoolkit/Project_code/interactive_map_main.py

# Create a Python script file named custom_themes_main.py inside the Project_code subdirectory
!touch dataviztoolkit/Project_code/custom_themes_main.py

# Commented out IPython magic to ensure Python compatibility.
# Execute the chart_builder_main.py script located in the Project_code subdirectory
# %run dataviztoolkit/Project_code/chart_builder_main.py

import pandas as pd

# Commented out IPython magic to ensure Python compatibility.
# Execute the interactive_map_main.py script located in the Project_code subdirectory
# %run dataviztoolkit/Project_code/interactive_map_main.py

# Commented out IPython magic to ensure Python compatibility.
# Execute the custom_themes_main.py script located in the Project_code subdirectory
# %run dataviztoolkit/Project_code/custom_themes_main.py

